language: ruby
rvm:
    - 2.1

localhost_regex: !ruby/regexp '(.*?(\blocalhost\b)[^$]*)$'

script: "bundle exec jekyll build && bundle exec htmlproof ./_site --href-ignore {{ localhost_regex }}"

branches:
    only:
        - master

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
