name:           Harsh Vakharia
url:            http://harshjv.github.io
logo:
  path:         /assets/images/logo.png
  alt:          Harsh Vakharia's blog logo
description:    Thoughts on technical stuff
markdown:       redcarpet
pygments:       true
permalink:      /blog/:title
author:
  name:         Harsh Vakharia
  email:
    link:       "mailto:&#104;&#097;&#114;&#115;&#104;&#106;&#118;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"
  docker:
    username:   harshjv
    link:       https://hub.docker.com/u/harshjv
  google_plus:
    username:   HarshVakhariaJ
    link:       https://plus.google.com/+HarshVakhariaJ
  linkedin:
    username:   harshjv
    link:       http://in.linkedin.com/in/harshjv
  twitter:
    username:   harshjv
    link:       https://twitter.com/harshjv
  github:
    username:   harshjv
    link:       https://github.com/harshjv
  gravatar:
    hash:       58ad5652420c75cc05a0920f2014ba2c
    link:       http://www.gravatar.com/avatar/58ad5652420c75cc05a0920f2014ba2c
  facebook:
    numeric_id: 1684195558
sass:
  sass_dir:     _sass
  style:        :compressed
disqus:
  shortname:    harshjv
